name: "AWS SAM"

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-deploy-SAM:
    runs-on: ubuntu-latest
    env: 
      AWS_SAM_S3_ARTIFACT: pgr301-sam-bucket
      AWS_BUCKET_NAME: candidate2014
      AWS_STACK_NAME: candidate2014

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Build
        working-directory: kjell/
        run: |
          sam build --use-container
      
      - name: Deploy
        working-directory: kjell/
        if: github.ref_name == 'main' && github.event_name == 'push'
        run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
            --s3-bucket ${{ env.AWS_SAM_S3_ARTIFACT }} --region ${{ secrets.AWS_REGION }} \
            --parameter-overrides BUCKET_NAME=${{ env.AWS_SAM_S3_ARTIFACT }} REGION=${{ secrets.AWS_REGION }}
            --stack-name ${{ env.AWS_STACK_NAME }} 
          